### ISSUE TITLE
[NEXT] ( QUESTION ) Groups ?

### ISSUE THREAD

**Issue by scopefragger** [COCOPi/cockpit#531]
It looks like there is a group permissions functionality,  however there seems like there is no way to set groups and permissions?  OR have i just misplaced this functionality as I've been implementing my own elements.

**Comment by gryphonmyers** [comment]
Yeah we could really use some docs! The group specifications go in the config. Whether you have a yaml or php config file, the syntax may differ but it should look something like this (I just cped this out of my config.php):

'''
"groups" => [
        "contentEditor" => [
            '$vars' => [
                "finder.path" => "storage/uploads"
            ],
            "collections" => [
                "create" => false,
                "delete" => false
            ]
        ],
        "developer" => [
            '$vars' => [
                "finder.path" => "storage/uploads"
            ],
            "collections" => [
                "create" => false,
                "delete" => false
            ]
        ]
    ]
'''

Once you have created the group, you can give more granular collection control via the "access" tab on the collection view.

**Comment by scopefragger** [comment]
Ace,. That's perfect
And haha yea docs would be amazing. We have most of what we want working
its just the small bits like complex filter statements via the collection
modual

To be honest, Where's the best place to ask about things ? Here as issue or
...

**Comment by gryphonmyers** [comment]
Probably here, yup. No guarantee anyone will respond, but I am pretty regularly browsing issues and I try to answer questions when I can. Some things only @aheinze can answer though, since it's his codebase.

**Comment by scopefragger** [comment]
Haha well any help is much apreachated.

If I get time I'll try and post back a few things we build, Might help
other new starters

**Comment by aheinze** [comment]
Hi,

I know that the current situation is unacceptable but I'm already working on the new docs and hope  to get it online next month. Fingers crossed 🤞

Greets,
Artur

**Comment by scopefragger** [comment]
**next month** ? Ace,  to be honest ive been able to work most things out by just reading your code,  its bit this this question where the plot was lost, ha!

**Comment by gryphonmyers** [comment]
> I'm already working on the new docs and hope to get it online next month.

Great to hear! That's exciting news. 

This issue can probably be closed now, yeah?

**Comment by scopefragger** [comment]
Yea,  ha!

**Comment by ThomasThiemann** [comment]
> Yeah we could really use some docs! The group specifications go in the config. Whether you have a yaml or php config file, the syntax may differ but it should look something like this (I just cped this out of my config.php): [..]

Thanks Gryphon! Your posting made it quite easy to create groups for me.

---

If anyone can't figure out how to create groups in the config.yaml file I "translated" the example above and tested it for Cockpit 0.5.5.
Just open the _/path/to/cockpit/config/config.yaml_ file and paste the following block.
This will add the groups **contentEditor** and **developer**.

```
groups:
        contentEditor:
         '$vars':
                finder.path: "storage/uploads"
                collections:
                        create: false
                        delete: false
        developer:
         '$vars':
                finder.path: "storage/uploads"
                collections:
                        create: false
                        delete: false
```
